development: &default
  adapter: postgresql
  database: docker_ruby_2_2_0_rails_4_2_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: <%= ENV['DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['DB_1_PORT_5432_TCP_PORT'] %>

test:
  <<: *default
  database: docker_ruby_2_2_0_rails_4_2__test